"""
Image serving API
Serves annotated images generated by the agent
"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/images", tags=["images"])

# Annotated images directory
ANNOTATED_IMAGES_DIR = Path(__file__).parent.parent.parent / "annotated_images"


@router.get("/{session_id}.jpg")
async def get_annotated_image(session_id: str):
    """
    Get annotated image for a session

    Args:
        session_id: Session ID

    Returns:
        JPEG image file

    Raises:
        404: If image not found
    """
    image_path = ANNOTATED_IMAGES_DIR / f"{session_id}.jpg"

    if not image_path.exists():
        logger.warning(f"Annotated image not found: {session_id}")
        raise HTTPException(
            status_code=404,
            detail=f"No annotated image found for session {session_id}"
        )

    logger.info(f"Serving annotated image: {session_id}")

    return FileResponse(
        path=image_path,
        media_type="image/jpeg",
        filename=f"annotated_{session_id}.jpg"
    )


@router.delete("/{session_id}.jpg")
async def delete_annotated_image(session_id: str):
    """
    Delete annotated image for a session

    Args:
        session_id: Session ID

    Returns:
        Success message
    """
    image_path = ANNOTATED_IMAGES_DIR / f"{session_id}.jpg"

    if image_path.exists():
        image_path.unlink()
        logger.info(f"Deleted annotated image: {session_id}")
        return {"status": "deleted", "session_id": session_id}

    return {"status": "not_found", "session_id": session_id}
